/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

public class App {

    public static void main(String[] args) {
        //////////////// Exercicio 1 - Lampada//////////////
        Lampada lampadaUm = new Lampada();
        lampadaUm.ligar();
        if (lampadaUm.verEstado()) {
            System.out.println("Ligada");
        } else {
            System.out.println("Desligada");
        }

        Lampada lampadaDois = new Lampada();
        lampadaDois.desligar();
        if (lampadaDois.verEstado()) {
            System.out.println("Ligada");
        } else {
            System.out.println("Desligada");
        }

        //////////////// Exercicio 2 - Pessoa//////////////
        Pessoa alice = new Pessoa("Alice", 22);
        Pessoa bruno = new Pessoa("Bruno", 25);

        bruno.felizAniversario();
        bruno.felizAniversario();
        bruno.felizAniversario();

        System.out.println(bruno.getIdade() + " " + alice.getIdade());

        try {
            alice.setIdade(-44);
        } catch (IllegalArgumentException e) {
            System.out.println("Erro ao definir idade: " + e.getMessage());
        }
        System.out.println(alice.getIdade());

        try {
            bruno.setNome("    ");
        } catch (IllegalArgumentException e) {
            System.out.println("Erro ao definir nome: " + e.getMessage());
        }
        System.out.println(bruno.getNome());

        //////////////// Exercicio 3 - Retangulo//////////////
        Retangulo retanguloUm = new Retangulo(1, 1);
        // retanguloUm.setAltura(4);
        // retanguloUm.setLargura(5);
        // System.out.println(retanguloUm.getArea());
        // System.out.println(retanguloUm.getPerimetro());
        System.out.println("Maior Retangulo: " + Retangulo.maiorRetangulo);
        System.out.println("Menor Retangulo: " + Retangulo.menorRetangulo);

        Retangulo retangulo2 = new Retangulo(12, 12);

        System.out.println("Maior Retangulo: " + Retangulo.maiorRetangulo);

    }
}
